---

- name: Configure virtual aliases
  lineinfile: "dest={{postfix_virtual}} regexp='^{{ item.alias }}' line='{{ item.alias }}\t {{ item.user }}' backup=yes create=yes"
  with_items: virtual_aliases
  notify: postmap virtual aliases
  when: virtual_aliases > 0
  tags: config_virtual_aliases
