---

# smtp_sasl
- name: Configure {{postfix_main_cf}}
  lineinfile: >
    dest="{{postfix_main_cf}}"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
  with_items:
    - { regexp: "^smtp_sasl_auth_enable", line: "smtp_sasl_auth_enable = yes" }
    - { regexp: "^smtp_tls_security_level",
        line: "smtp_tls_security_level = {{postfix_main_cf_smtp_tls_security_level_YES}}" }
    - { regexp: "^smtp_sasl_tls_security_options",
        line: "smtp_sasl_tls_security_options = {{postfix_main_cf_smtp_sasl_tls_security_options}}" }
  when: postfix_main_cf_smtp_sasl_auth_enable == "yes"
  notify: reload postfix
  tags: config_potfix_main_cf_smtp_sasl

- name: Configure {{postfix_main_cf}}
  lineinfile: >
    dest="{{postfix_main_cf}}"
    regexp="{{item.regexp}}"
    line="{{item.line}}"
    backup="yes"
  with_items:
    - { regexp: "^smtp_sasl_auth_enable", line: "smtp_sasl_auth_enable = no" }
    - { regexp: "^smtp_tls_security_level",
        line: "smtp_tls_security_level = {{postfix_main_cf_smtp_tls_security_level_NO}}" }
  when: postfix_main_cf_smtp_sasl_auth_enable == "no"
  notify: reload postfix
  tags: config_potfix_main_cf_smtp_sasl

# smtp_sasl_password_maps
- name: Configure smtp_sasl_password_maps in {{postfix_main_cf}}
  lineinfile: >
    dest="{{postfix_main_cf}}"
    regexp="^smtp_sasl_password_maps"
    line="smtp_sasl_password_maps = hash:{{postfix_main_cf_smtp_sasl_password_maps}}"
    backup="yes"
  when:
    - not("postfix_main_cf_smtp_sasl_password_maps" | trim == "")
    - postfix_main_cf_smtp_sasl_auth_enable == "yes"
  notify: reload postfix
  tags: config_potfix_main_cf_smtp_sasl_password_maps

# smtp_sasl_passwords
- name: Configure SMTP SASL passwords in {{postfix_main_cf_smtp_sasl_password_maps}}
  lineinfile: >
    dest="{{postfix_main_cf_smtp_sasl_password_maps}}"
    regexp="{{item.relayhost}}"
    line="{{item.line}}"
    create="yes"
    owner="root"
    group="wheel"
    mode="0640"
    backup="yes"
  with_items: "{{postfix_smtp_sasl_passwords}}"
  notify: postmap smtp sasl passwords
  tags: config_potfix_smtp_sasl_passwords
