---

- name: Delete sendmail from /etc/mail/mailer.conf
  lineinfile: >
    dest="/etc/mail/mailer.conf"
    regexp="{{ item.regexp }}"
    state="absent"
  with_items:
    - { regexp: "^#.*" }
    - { regexp: "^hoststat.*" }
    - { regexp: "^purgestat.*" }
  tags: config_mailer_conf

- name: Configure postfix in /etc/mail/mailer.conf
  lineinfile: >
    dest="/etc/mail/mailer.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "^sendmail",  line: "sendmail /usr/local/sbin/sendmail"}
    - { regexp: "^send-mail",  line: "send-mail /usr/local/sbin/sendmail"}
    - { regexp: "^mailq",  line: "mailq /usr/local/sbin/sendmail"}
    - { regexp: "^newaliases",  line: "newaliases /usr/local/sbin/sendmail"}
  notify: restart postfix
  tags: config_mailer_conf
