---
# tasks file for freebsd-mailserver

- include: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - freebsd-mailserver-packages
    - freebsd-mailserver

- include: create_files.yml
  tags:
    - freebsd-mailserver-create_files
    - freebsd-mailserver

- include: create_certificates.yml
  tags:
    - freebsd-mailserver-create_certificates
    - freebsd-mailserver

- include: config_rc_conf.yml
  tags:
    - freebsd-mailserver-config_rc_conf
    - freebsd-mailserver

- include: config_mailer_conf.yml
  tags:
    - freebsd-mailserver-config_mailer_conf
    - freebsd-mailserver

- include: config_periodic_conf.yml
  tags:
    - freebsd-mailserver-config_periodic_conf
    - freebsd-mailserver

- include: config_postfix.yml
  tags:
    - freebsd-mailserver-config_postfix
    - freebsd-mailserver

- include: config_postfix_sasl.yml
  tags:
    - freebsd-mailserver-config_postfix_sasl
    - freebsd-mailserver

- include: config_postfix_master.yml
  tags:
    - freebsd-mailserver-config_postfix_master
    - freebsd-mailserver

- include: config_virtual_aliases.yml
  tags:
    - freebsd-mailserver-config_virtual_aliases
    - freebsd-mailserver

- include: config_aliases.yml
  tags:
    - freebsd-mailserver-config_aliases
    - freebsd-mailserver

- include: config_dovecot.yml
  tags:
    - freebsd-mailserver-config_dovecot
    - freebsd-mailserver
